Task 5 update 7

diff --git a/0x05-processes_and_signals/5-dont_stop_me_now b/0x05-processes_and_signals/5-dont_stop_me_now
--- a/0x05-processes_and_signals/5-dont_stop_me_now
+++ b/0x05-processes_and_signals/5-dont_stop_me_now
@@ -1,11 +1,18 @@
 #!/usr/bin/env bash
 # This script stops the 4-to_infinity_and_beyond process
 
-# Search and terminate the process using pkill
-pkill -f "4-to_infinity_and_beyond"
+# Get the process ID of 4-to_infinity_and_beyond
+pid=$(pgrep -f "4-to_infinity_and_beyond")
 
-if [[ $? -eq 0 ]]; then
-    echo "Process terminated"
+if [[ -n $pid ]]; then
+    # Terminate the process
+    kill $pid
+    
+    if [[ $? -eq 0 ]]; then
+        echo "Process terminated"
+    else
+        echo "Failed to terminate the process"
+    fi
 else
     echo "Process not running"
 fi
